### ISSUE TITLE
ps2: Keypresses cause kernel to hang

### ISSUE THREAD

**Issue by notYuriy** [FlorenceOS/Florence#46]
If keypresses are spammed right after boot, it is possible to make kernel to hang like here
![image](https://user-images.githubusercontent.com/43564204/118140978-8f816e00-b411-11eb-94a6-c23002da5804.png)
It is not known which subsystem causes that.

**Comment by N00byEdge** [comment]
This may be due to an interrupt arriving before routing them to the CPU, as can be seen here, the IOAPIC has a pending keyboard interrupt but the LAPIC is oblivious to it:
![image](https://user-images.githubusercontent.com/2322546/118144228-7d510100-b40c-11eb-8886-a7d82a11d4c4.png)

**Comment by notYuriy** [comment]
Fixed by draining PS2 keyboard buffer

**Comment by N00byEdge** [comment]
No, the commit linked in the close

**Comment by N00byEdge** [comment]
Problem was pressing a key and interrupting by printing during printing, and probably messing up some logger state (maybe virtio?)
