### ISSUE TITLE
mem: Page sizes

### ISSUE THREAD

**Issue by notYuriy** [FlorenceOS/Florence#49]
Current API to get page sizes is a mess. As a case study, what should be a correct way to determine page size for the shared memory object that can be mapped both in user and kernel space?

**Comment by N00byEdge** [comment]
On this: I'm heavily considering dropping the second arugment to `page_size()` and just enforcing uniform page sizes for the entire address space.

**Comment by notYuriy** [comment]
I agree. We would need universe page sizes anyways since some memory objects could be shared between kernel and user processes

**Comment by notYuriy** [comment]
Reopening since the function for getting page sizes still requires context
