### ISSUE TITLE
thread: Mutex initialization

### ISSUE THREAD

**Issue by notYuriy** [FlorenceOS/Florence#68]
Mutexes are not initialized everywhere as they should be.
For instance, `std.heap.GeneralPurposeAllocator` does not initialize `os.thread.Mutex` it uses for locking.
https://github.com/FlorenceOS/Florence/blob/6e68f8e5f8ece53dca2bdf5667f185cc3aee9ada/src/memory/vmm.zig#L59-L65.
Not initializing mutex could potentially cause a lot of bugs, since mutex code assumes the atomic queue inside it is fully initialized

Bug should be fixed by making mutexes lazily initialized or by making atomic queue function without init() method.

**Comment by N00byEdge** [comment]
I'd honestly just get rid of all usages of `std.heap.GeneralPurposeAllocator` with a non-std mutex

**Comment by notYuriy** [comment]
GPA from stdlib implements a lot of slab logic anf helps to boost allocations. I don't think removing GPA would be a good option here.

Instead, atomic queue should support init with .{} if possible so we can statically init atmcqueues.
